### ISSUE TITLE
Architecture detection flappy

### ISSUE THREAD

**Issue by seebeen** [oblakstudio/ddev-ioncube#53]
As noted by @stasadev

It doesn't install on my Arch-based Linux, because I don't have this command:

```
./web-build/ioncube/download-loaders: line 4: /usr/bin/arch: No such file or directory
```

Maybe better use `uname -m` for the architecture check?

**Comment by stasadev** [comment]
For the context https://www.gnu.org/software/coreutils/manual/html_node/arch-invocation.html

> `arch` is not installed by default, so portable scripts should not rely on its existence.
